(define *title* "Geolocation Test")
(define *description* "A test of the `geolocation` feature. Logs your geolocation data every time it updates.")
(define *category* "Testing")
(chain (gps) :pos ::1 (log ::0 "Position updated! ")
    ~ @gps :altitude ::1 (log ::0 "Altitude updated! ")
    ~ @gps :heading ::1 (log ::0 "Heading updated! ")
    ~ @gps :speed ::1 (log ::0 "Speed updated! "))
